import express from 'express';
import cors from 'cors';
import authRoutes from './routes/authRoutes.js';
import productRoutes from './routes/productRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import { notFound,errorHandler } from './middleware/error.js';
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json());
app.get('/api/health',(req,res)=>res.json({success:true,message:'LocalHarvest API is running'}));
app.use('/api/auth',authRoutes); app.use('/api/products',productRoutes); app.use('/api/orders',orderRoutes); app.use('/api/admin',adminRoutes); app.use(notFound); app.use(errorHandler); export default app;
